// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/backend/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/[...path]').default>>>>
    }
    '/api/backend/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/auth/login.post').default>>>>
    }
    '/api/backend/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/auth/logout.post').default>>>>
    }
    '/api/backend/geo/communes/:provinceCode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/geo/communes/[provinceCode].get').default>>>>
    }
    '/api/backend/geo/province/:provinceCode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/geo/province/[provinceCode].get').default>>>>
    }
    '/api/backend/geo/provinces/:regionCode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/geo/provinces/[regionCode]/index.get').default>>>>
    }
    '/api/backend/listings/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/listings/[id].get').default>>>>
    }
    '/api/backend/listings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/listings/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/listings/index.post').default>>>>
    }
    '/api/backend/public/listings/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/public/listings/[id].get').default>>>>
    }
    '/api/backend/public/listings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/backend/public/listings/index.get').default>>>>
    }
    '/storage/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/storage/[...path]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}